### ISSUE TITLE
railroad logo ideas

### ISSUE THREAD

**Issue by Shoalsteed** [eyedeekay/railroad#1]
![1](https://user-images.githubusercontent.com/50714166/120863581-c9e5b300-c558-11eb-8532-5e0189c1dea6.png)
![2](https://user-images.githubusercontent.com/50714166/120863582-c9e5b300-c558-11eb-8d46-cbe98781cd5c.png)

**Comment by eyedeekay** [comment]
Closing because we finished this years ago
